spring.application.name=tasktracker

# Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/task_tracker
spring.datasource.username=task_user
spring.datasource.password=task_password
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT Secret (for development only, not for production)
jwt.secret=94a08da1fecbb6e8b46990538c7b50b2b8106f2e2d094ebfa2cb233ab3631f42
jwt.expirationMs=86400000

# Server port
server.port=8080
